stages:
  - test
  - build

test-source-code:
  stage: test
  image: node:14-alpine
  artifacts:
    reports:
      junit:
        - coverage/clover.xml
    paths:
      - coverage
  script:
    - echo "Test"
    - npm i
    - npm run test