
FROM node:14 as build

WORKDIR /app

COPY package*.json .

RUN npm i --only=production

RUN mv node_modules/ prod_modules/

RUN npm i

RUN npm run build

RUN rm -rf node_modules

FROM node:14-alpine as production

COPY --from=build prod_modules/ node_modules/
COPY [".sequelizerc","package.json","./"]
COPY ./ ./

CMD ["npm", "run", "start"]